#!/usr/bin/env bash
# Sharded ablation sweep: one SLURM job per target cell line (parallel), then a
# dependent aggregation job that concatenates the shards and builds ONE report.
# Wall time ~ a single line (~20-40 min) instead of the sum over lines.
#
# Usage:
#   scripts/launch_ablation_sweep.sh [N_LINES]
#   JOINT=1 scripts/launch_ablation_sweep.sh 12          # multitask GP
#   SEEDS="0 1 2" TAG=indep scripts/launch_ablation_sweep.sh 12
# Env: SEEDS (default "0 1"), JOINT (empty=independent), TAG, EXPORTFIGS.
set -euo pipefail
N_LINES="${1:-12}"
SEEDS="${SEEDS:-0 1}"; JOINT="${JOINT:-}"; TAG="${TAG:-${JOINT:+joint}${JOINT:-indep}}"
PANEL_A="${PANEL_A:-none}"; PANEL_B="${PANEL_B:-data/processed/depmap/panel_5k.txt}"
EMB="${EMB:-data/processed/embeddings/pubmedbert_all.parquet}"
GE="data/processed/depmap/gene_effect.parquet"
TS="$(date +%Y%m%d-%H%M%S)"; ROOT="res/runs_ablation/sweep_${TAG}_${TS}"; mkdir -p "$ROOT" logs

# number of distinct contrast lines (same set for every target line). Default 1.
NCON="${CONTRASTS:-1}"
# CONTRAST_IDS (optional): explicit space-separated contrast ModelIDs; overrides
# the auto rank_contrast_lines selection.
CONTRAST_IDS="${CONTRAST_IDS:-}"
# 1. Deterministic target lines + contrast line(s) -> ROOT/lines.txt, ROOT/contrast.txt
micromamba run -n geneal python - "$GE" "$EMB" "$N_LINES" "$ROOT" "$NCON" "$CONTRAST_IDS" <<'PY'
import sys
import pandas as pd
from geneal.data.depmap import load_gene_effect, parse_entrez
from geneal.data.selective import rank_contrast_lines
ge_path, emb_path, n_lines, root, ncon = sys.argv[1:6]
explicit = sys.argv[6].split() if len(sys.argv) > 6 and sys.argv[6].strip() else None
n_lines = int(n_lines); ncon = int(ncon)
ge = load_gene_effect(ge_path); emb = pd.read_parquet(emb_path)
embset = set(emb.index)
labs = [g for g in ge.index if parse_entrez(g) in embset]
contrasts = explicit if explicit else rank_contrast_lines(ge, n=max(10, ncon))[:ncon]
cset = set(contrasts)
ranked = ge.loc[labs].isna().sum(axis=0).sort_values().index.tolist()
lines = [c for c in ranked if c not in cset][:n_lines]
open(f"{root}/lines.txt", "w").write("\n".join(lines) + "\n")
open(f"{root}/contrast.txt", "w").write(" ".join(contrasts))   # space-joined
print(f"{len(lines)} lines, contrasts={contrasts}")
PY
CONTRAST="$(cat "$ROOT/contrast.txt")"   # space-joined contrast ModelIDs
NL="$(grep -c . "$ROOT/lines.txt")"
echo "sweep -> $ROOT  ($NL lines x [$SEEDS] seeds, JOINT='${JOINT}', contrasts=[$CONTRAST])"

# persist the exact reproducible launch command into the run dir (the report links it)
cat > "$ROOT/launch.sh" <<EOF
#!/usr/bin/env bash
# Reproduces this ablation sweep ($ROOT). Generated by scripts/launch_ablation_sweep.sh.
CONTRASTS="${NCON}" CONTRAST_IDS="${CONTRAST_IDS}" JOINT="${JOINT}" SEEDS="${SEEDS}" \\
  TAG="${TAG}" PANEL_A="${PANEL_A}" PANEL_B="${PANEL_B}" EMB="${EMB}" \\
  bash scripts/launch_ablation_sweep.sh ${N_LINES}
EOF
chmod +x "$ROOT/launch.sh"

# 2. One array task per line (parallel).
ARRAY_ID=$(sbatch --parsable --array="0-$((NL-1))" \
    --export=ALL,ROOT="$ROOT",SEEDS="$SEEDS",JOINT="$JOINT",CONTRAST="$CONTRAST",EMB="$EMB",PANEL_A="$PANEL_A",PANEL_B="$PANEL_B",ANALYSES="${ANALYSES:-both}" \
    jobs/ablation_shard.sh)
echo "shard array job: $ARRAY_ID"

# 3. Aggregation, runs only if all shards succeed.
AGG_ID=$(sbatch --parsable --dependency="afterok:${ARRAY_ID}" \
    --export=ALL,ROOT="$ROOT" jobs/ablation_aggregate.sh)
echo "aggregation job: $AGG_ID (afterok:$ARRAY_ID)"
echo "report will land at: $ROOT/report.html"
